name: Build and Publish Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build binary
        run: dotnet publish --configuration Release --output binaries --self-contained --runtime win-x64

  upload:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Copy binaries
        run: cp -r binaries/. artifacts/

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: artifacts/
