name: Publish Binaries

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Build and Publish for Windows x64
        run: dotnet publish -r win-x64 --configuration Release -o binaries/win-x64

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: v2.0
          release_name: Release v2.0
          draft: false
          prerelease: false
          token: ${{ secrets.PAT }}

      - name: Upload Binaries
        id: upload-binaries
        uses: actions/upload-artifact@v2
        with:
          name: Windows Binaries
          path: binaries/win-x64

      - name: Attach Release Assets
        id: attach-assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ steps.upload-binaries.outputs.artifact_paths }}
          asset_name: binaries-win-x64.zip
          asset_content_type: application/zip
