name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'  # Use the '6.0' tag to fetch the latest stable version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build binaries
        run: dotnet build --configuration Release

      - name: Publish binaries
        run: dotnet publish --configuration Release --output ./binaries --self-contained true --runtime linux-x64
