name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build binaries
        run: dotnet build --configuration Release

      - name: Publish binaries
        run: dotnet publish --configuration Release --output ./binaries --self-contained true --runtime linux-x64

  publish:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish for macOS
        run: dotnet publish --configuration Release --output ./binaries --self-contained true --runtime osx-x64

      - name: Publish for Windows (32-bit)
        run: dotnet publish --configuration Release --output ./binaries --self-contained true --runtime win-x86

      - name: Publish for Windows (64-bit)
        run: dotnet publish --configuration Release --output ./binaries --self-contained true --runtime win-x64

  upload:
    needs: publish

    runs-on: ubuntu-latest

    steps:
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: binaries
