name: Publish Binaries

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Build and Publish for Windows x64
        run: dotnet publish -r win-x64 --configuration Release -o binaries/win-x64

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          name: Windows Binaries
          path: binaries/win-x64
