name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build for Windows
      run: dotnet publish -r win-x64 --configuration Release /p:PublishSingleFile=true

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path: |
          bin/Release/net6.0/win-x64/YourAppName.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.1
        release_name: Release v1.1
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          ${{ needs.build.outputs.artifacts }}/YourAppName.exe
        asset_name: YourAppName
